# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool: NV31

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    # echo "rocm" | sudo -S apt install libva-amdgpu-dev libdrm-amdgpu1 mesa-amdgpu-va-drivers
    # echo "rocm" | sudo -S apt install cmake
    # echo "rocm" | sudo -S apt install pkg-config
    # echo "rocm" | sudo -S apt install ffmpeg libavcodec-dev libavformat-dev libavutil-dev
    # echo "rocm" | sudo -S apt install libstdc++-12-dev
    echo "rocm" | sudo -S python3 rocDecode-setup.py
    mkdir build && cd build
    cmake ../
    make -j8
    sudo make install
    make test
  displayName: 'Run a multi-line script'
