# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo "rocm" | sudo -S python3 rocDecode-setup.py
    mkdir build && cd build
    cmake ../
    make -j8
    sudo make install
  displayName: 'Run a multi-line script'
